### ISSUE TITLE
"FML has found a non-mod file RaspberryJamMod-0.08.jar in your mods directory"

### ISSUE THREAD

**Issue by JeromeJ** [arpruss/raspberryjammod#1]
Hello, this is the error I ran into:

[Client thread/INFO] [FML]: FML has found a non-mod file RaspberryJamMod-0.08.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.

Had a hard time figuring out how to install your mod, had to do a lot of Googling.
So I did install gradle and JDK (as gradle asked for it) and ran gradle build in the same directory as build.gradle.

Got the build/libs/RaspberryJamMod-0.08.jar after completion, which I placed in the minecraft/mods folder.

I don't know with which version your mod is supposed to work with (that might be the issue), I'm running Minecraft 1.7.10.

Thanks a lot in advance. I really want to do some Python in Minecraft, and your mod is the closest I have been to realizing that small dream of mine :)

**Comment by arpruss** [comment]
Have you installed the Forge?

**Comment by JeromeJ** [comment]
Yes, I'm installing it on the FTB Resurrection pack, which includes Forge by default.

I managed to make https://github.com/kbsriram/mcpiapi/ running, but to be honest, I'm not sure what are the differences between your mod and this one. If I understood well, yours might be more specific? Anyway, I never touched any Raspberry thing before. Initially I was just struggling to find a way to execute Python in Minecraft.

Thanks for the feedback! Looking for your answer.

**Comment by arpruss** [comment]
The main difference is that mine is for 1.8.

**Comment by JeromeJ** [comment]
So that's the source of this unfriendly error from FML?
I hope it is that, at least we know then.

I was afraid yours was for 1.8 but I wasn't sure. Thanks for your support!

**Comment by JeromeJ** [comment]
Btw, I come from your post here: http://raspberrypi.stackexchange.com/a/26958/28381
Might be nice having version info related directly in your answer there (or I can comment it too alternatively).

**Comment by arpruss** [comment]
I added more detailed description to the stackexchange post, though since I am now using a different account it's awaiting peer review.

**Comment by JeromeJ** [comment]
Repost the answer with your proper answer to get your rep on your right account?

Sure you'll get some rep with that high quality answers with so many links and all.
