### ISSUE TITLE
NameError: name 'security' is not defined

### ISSUE THREAD

**Issue by frjaraur** [arpruss/raspberryjammod#10]
Tying to use raspberryjammod on non-bukkit server. I followed install instructions and located code asking for security, but I don't really know how to avoid this error (install issue or needs another module??).
Traceback (most recent call last):
  File "helloworld.py", line 5, in <module>
    mc = minecraft.Minecraft()
  File "/home/user/.minecraft/mcpipy/mcpi/minecraft.py", line 193, in __init__
    if security.AUTHENTICATION_USERNAME and security.AUTHENTICATION_PASSWORD:
NameError: name 'security' is not defined

Many Thanks,
Javier R.

**Comment by arpruss** [comment]
Can you get the latest pythonX-scripts/mcpipy/mcpi/minecraft.py from the repository and see if the problem persists? I think I fixed the bug.

**Comment by frjaraur** [comment]
Many Thanks, Great work, I added to my dockerized minecraft project as and option if users use it with your mod (https://github.com/frjaraur/DockerizedMinecraftServer).
Regards,
Javier R.
