### ISSUE TITLE
build.sh fails on Linux

### ISSUE THREAD

**Issue by neuhaus** [arpruss/raspberryjammod#11]
There are no build instructions for RaspberryJamMod.jar.

So I ran build.sh
On Linux, build.sh starts 19/fast.sh which in turn tries to run the gradlew.bat for windows (which fails).

Btw, what's up with these numerical directory names? I can't tell what sub-projects they contain.

**Comment by arpruss** [comment]
Yeah, it's a mess. But it works for me. :-) I'll try to add more information on building and directory structure.

**Comment by arpruss** [comment]
You can now try:
 sh build.sh noinstall noinstaller
and see if that works for you.

**Comment by neuhaus** [comment]
Looks good, thanks.
