### ISSUE TITLE
mod not working on 32bit Windows 7 system

### ISSUE THREAD

**Issue by neuhaus** [arpruss/raspberryjammod#13]
I have a dozen of old notebook computers at my disposal that I want to use to do a programming workshop for kids with Minecraft and Python. They have 2 GB of memory and run Windows 7 (32bit).

I first started using the Raspberry Juice mod for bukkit. However, memory is very low and I figured it would be better not to run a standalone server in addition to the client on the same machine.

So I tried to install the Raspberry Jam Mod. I used the latest java 8 (-101), the latest forge (I believe 1.10.2 - 12.18.1.2092) and the installer provided by Raspberry Jam Mod release 0.8.2 (installing Python 3).

Minecraft crashes during loading. The last entry in the log is about the raspberry jam mod. However, there is no stack trace.

The mod works without problems on a beefier PC with the 64bit version of Windows 10 and Java 8.
Any ideas?

**Comment by dallasspohn** [comment]
It crashes during load with the rbjm? But loads fine with out it? was anything written to event viewer?  
In my experience it is always the Java crashing when my students install and run.

**Comment by arpruss** [comment]
Send me a zip of the log files from .Minecraft/logs

**Comment by neuhaus** [comment]
Ok i have to get back to the machine i question

**Comment by arpruss** [comment]
I can try to fix this given the log...

**Comment by neuhaus** [comment]
I received the machine yesterday, upgraded the memory to 4GB and installed Windows 7 64bit. So I may not be able to provide you with a log for a while since I'm no longer affected by the issue. The notebooks were pretty much unusable with 2GB RAM and HDDs anyway.
