### ISSUE TITLE
whereami call returns an error

### ISSUE THREAD

**Issue by fluidz91** [arpruss/raspberryjammod#14]
Hi,

I have installed RaspberryJamMod-Installer.exe 0.82 and was able to execute donut and shuttle (though i died because of suffocation).
Anyway, when i execute /py whereami, I have the following error :

`[ERR] Traceback (most recent call last):
[ERR] File "whereami.py, line 4, in <module>
[ERR] mc.postToChat(mc.player.getTilePos())
[ERR] File "C:\Users\.....\.minecraft\mcpPY\mcpi\minecraft.py", line
385, in postToChat
[ERR] self.conn.send("chat.post", msg.replace("\r", " ").replace("\n", " "))
[ERR] AttributeError: 'Vec3' object has no attribute 'replace'`

I am very new to Python and Minecraft API.
I tried mc.postToChat("HELLO WORLD !") and it works correctly.

Thank you

**Comment by arpruss** [comment]
Fixed. Replace mcpi/minecraft.py with the one in the next release or in github. Thanks for the report.
