### ISSUE TITLE
Nothing for FTB/1.7.10?

### ISSUE THREAD

**Issue by vanjavk** [arpruss/raspberryjammod#15]
FTB is pretty much all using 1.7.10, I wanted to install this mod to potentionally show my beam.pro chat inside minecraft, but apparently there's not even a version for 1.7.10 :/
Is it hard to build a .jar for 1.7.10? If not... Pleaaaasee :)

**Comment by arpruss** [comment]
Hard enough that I don't want to do it. A lot of changes to the source code would be needed. There is the mcpiapi mod, though, for 1.7.10.
