### ISSUE TITLE
init for py

### ISSUE THREAD

**Issue by wangjunyi2008** [arpruss/raspberryjammod#16]
wow very cool job! really like the work ~

would it be possible for loading the python script(s) when the world initializes?
(e.g. loading a series of scripts from a configure file)
it's possibile to utilize the mod to create new mod-like scripts for pythoners, but it would be inconvenient to ask the players run "/py" command and play the scripts. so would it be possible to add the feature in future?

thx

**Comment by arpruss** [comment]
I don't see adding this right now.
Can a command block be used somehow? Command blocks can launch /py scripts.
