### ISSUE TITLE
Doesn't work on servers

### ISSUE THREAD

**Issue by FliegendeWurst** [arpruss/raspberryjammod#18]
When I try to enter ```/py anything``` I just get some variation of "command not found".. do you know of any server where this mod works? :)

**Comment by arpruss** [comment]
You need a stock server with Forge and RaspberryJamMod installed server-side.

I know of one person who runs a server with RJM, but I am not authorized to disclose the information.

Failing a server with RJM, you can install the mod on the client side, turn on read-only mode in RaspberryJamMod's settings, and then run scripts--but the scripts won't actually change anything in the world, but will only look like they are changing it. And if the server has flying disabled, then weird things will happen if you build something with a script and go up on it--the server will think you're flying and will pull you back down.

**Comment by FliegendeWurst** [comment]
Thanks! Activating the client-only API fixed it :+1:
