### ISSUE TITLE
Create the used folders

### ISSUE THREAD

**Issue by Frontrider** [arpruss/raspberryjammod#24]
A little request from me: can you create the folders what you use during init? (if they don't exist)

**Comment by arpruss** [comment]
Which folders?

**Comment by Frontrider** [comment]
The mcpipy folder did not appeared after installation, and it was a little confusing.

**Comment by Frontrider** [comment]
misclick

**Comment by arpruss** [comment]
Did you install the scripts?

**Comment by Frontrider** [comment]
If you ask, if I used the exe installer, no I did not cause I am on linux so I decided not to try.
I did installed them, but it wasn't completly obvious where should I place them, since there is absolutly no documentation on it.

**Comment by arpruss** [comment]
The documentation is on the instructables page for this.
