### ISSUE TITLE
Clicking on the mod info crashes the game

### ISSUE THREAD

**Issue by Frontrider** [arpruss/raspberryjammod#25]
If I try to check the mod info in the menu (minecraft main menu->mods), the game crashes.

https://pastebin.com/MQVcKy3a

**Comment by arpruss** [comment]
What Forge and Minecraft versions are you using?

**Comment by Frontrider** [comment]
minecraft{1.12} [Minecraft] (minecraft.jar)
 mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
 FML{8.0.99.99} [Forge Mod Loader] (forgeBin-1.12-14.21.1.2387.jar)
 forge{14.21.1.2387} [Minecraft Forge] (forgeBin-1.12-14.21.1.2387.jar)

**Comment by denismm** [comment]
Seeing the same.  Same versions as frontrider.  I'm on OSX 10.9.5 if it matters.

**Comment by arpruss** [comment]
Try this version: https://github.com/arpruss/raspberryjammod/raw/master/mods.zip

**Comment by denismm** [comment]
That seems to work.

**Comment by arpruss** [comment]
Releasing that version as 0.92.
