### ISSUE TITLE
Entering Config view of the mod crashes Minecraft 1.12 on Windows 10

### ISSUE THREAD

**Issue by aivarannamaa** [arpruss/raspberryjammod#28]
Crash report:

```
The game crashed whilst updating screen events
Error: java.lang.AbstractMethodError: mobi.omegacentauri.raspberryjammod.GuiFactory.createConfigGui(Lnet/minecraft/client/gui/GuiScreen;)Lnet/minecraft/client/gui/GuiScreen;
```

**Comment by arpruss** [comment]
Which rjm version is this with?

**Comment by aivarannamaa** [comment]
0.92

**Comment by arpruss** [comment]
That's strange. I thought I fixed this as of 0.92. Were you upgrading from an earlier version or is this a fresh install?

**Comment by aivarannamaa** [comment]
All fresh. Yesterday I installed latest Minecraft, latest Forge and latest raspberry jam.

**Comment by arpruss** [comment]
When exactly did the crash happen?

**Comment by arpruss** [comment]
And did you use the exe installer or did you install manually?

**Comment by aivarannamaa** [comment]
I copied the mod manually. It happens when I start Minecraft and select Play Forge => Mods => Raspberry Jam Mod 0.90. 

It's weird that I see version 0.90 on the left side. Right side also mentions 0.92, Though:
![pilt](https://user-images.githubusercontent.com/1802/29993309-68e45884-8fbc-11e7-85bb-dcc8c0eff2fd.png)

After I click "Config" on this screen, I get 

![pilt](https://user-images.githubusercontent.com/1802/29993316-a6158462-8fbc-11e7-99cc-0a904fb90ec1.png)

I have Python 2.7, 3.5 and 3.5 installed. (BTW, how does the mod select the Python to use?)

**Comment by arpruss** [comment]
Can you tell me what is in your .minecraft/mods directory?

**Comment by arpruss** [comment]
Also, try removing all the stuff in .minecraft/mods and replacing it with the contents of the mods.zip from: https://github.com/arpruss/raspberryjammod/blob/master/mods.zip

**Comment by aivarannamaa** [comment]
Still the same. My mods directory was already empty before trying rjm first time.

**Comment by aivarannamaa** [comment]
Now I noticed that I had installed the **latest** Forge (1.12 - 14.21.1.2443) instead of the **recommended** version (1.12 - 14.21.1.2387). 

I now tried to install the recommended version over the previous (didn't find any unistall option). Looks like the downgrade didn't work -- Minecraft still reported previous versions.

If you tell me how to properly downgrade the Forge, then I can check whether the problem persists in recommended version.

**Comment by arpruss** [comment]
Try the version in https://github.com/arpruss/raspberryjammod/blob/master/mods.zip now. Thanks!

**Comment by aivarannamaa** [comment]
I'm now on a different computer (still Windows 10, still no other mods beside Forge and rjm). 

Now when I click on "Config", Minecraft just returns to title screen. The version numbers are now all 0.92 (no 0.90 anymore):

![image](https://user-images.githubusercontent.com/1802/30026041-e6649ab2-9183-11e7-81d2-ff3d7908db47.png)

**Comment by arpruss** [comment]
How about the new version I just committed?

**Comment by aivarannamaa** [comment]
Now I get the settings screen (but I'm already on third computer. I can check in the evening if it works also on my other compters).

**Comment by aivarannamaa** [comment]
Now it works also on my other computer. Thanks!
