### ISSUE TITLE
Unable to specify python version to use.

### ISSUE THREAD

**Issue by SophiaBronosky** [arpruss/raspberryjammod#3]
I've found that castle.py does not work with Python3. I have tried specifying the version in both the *.py files and in ~\AppData\Local\py.ini (Windows 10, sorry) but neither have any effect. See the attached files. (I added .txt to the end of the filenames to allow them to be attached) Any idea how to specify the python version to use?

Creating the py.ini file caused calling python at the shell to use python 2.7. Please help.

[version.py.txt](https://github.com/arpruss/raspberryjammod/files/72324/version.py.txt)
[version2.py.txt](https://github.com/arpruss/raspberryjammod/files/72323/version2.py.txt)
[version3.py.txt](https://github.com/arpruss/raspberryjammod/files/72325/version3.py.txt)
[py.ini.txt](https://github.com/arpruss/raspberryjammod/files/72326/py.ini.txt)

**Comment by arpruss** [comment]
1. Have you checked that you are using the python3 version of the script? (From python3-scripts/mcpipy.)
2. You can control which interpreter is used in the mod config, available from the main Minecraft menu.

**Comment by RichardBronosky** [comment]
I have replaced the mcpipy directory multiple times. I will look for the mod config.

-- (Sophia's father)

**Comment by RichardBronosky** [comment]
Thank you so much for the quick response! I have confirmed that changing the mod config worked. I open a Power Shell session and typed `py` and hit tab repeatedly to see all the executable options. They were `py.exe`, `python.exe`, `pythonw.exe`, `pyw.exe`, `C:\Python27\python.exe`, `C:\Python27\pythonw.exe`

The setting change I made was:
Main Menu > Mods > Raspberry Jam Mod > Config > Python Interpreter: c:\Python27\python.exe

(I'm leaving this here for anyone else who makes the unfortunate decision to purchase a Windows laptop for their child.)

**Comment by RichardBronosky** [comment]
I have also deleted the castle.py from my computer and re-extracted it from the zip file `python3-scripts.zip` in https://github.com/arpruss/raspberryjammod/releases/tag/0.51 I still get the same error. I'm attaching a screenshot.

![mc-castle-error](https://cloud.githubusercontent.com/assets/13620/12005822/b408ca6e-ab86-11e5-8774-5fdb3410c413.png)

**Comment by arpruss** [comment]
I've tested all the python 3 scripts currently included.
