### ISSUE TITLE
How to use camera

### ISSUE THREAD

**Issue by MatCorgi** [arpruss/raspberryjammod#32]
i cant get it to work, and the example uses some weird pygame functions that gave me errors

**Comment by arpruss** [comment]
These functions are only present in some Windows builds, I think.

**Comment by MatCorgi** [comment]
Well could you atleast show me examples? when i do mc.camera.setPos(0,30,0) nothing happens.

**Comment by arpruss** [comment]
Oh, that's completely different from the pygame stuff. 

Anyway, the in-game camera controls are an experimental extension to the API, and I haven't tried them for many versions.
