### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by Dodilei** [arpruss/raspberryjammod#34]
Hey
Is there some 'easy' way to add new commands to the mod?
I'm doing a game in Mc with command blocks and redstone, but it would be a lot easier and less space consuming if I could execute these commands externally like what you can do with Raspberryjam and python. However I use a lot of commands that are not in Mcpipy.
If it's not possible to add new commands, do you know some other mod or program that I can use to do this?

**Comment by Dodilei** [comment]
Now I was thinking that in 1.8 you have the /execute command, adding just it to the mod would allow you to execute all the others. It would work very well because it doesn't have connection to the entity that executed it, so you would not get problems with it being executed by no one.

**Comment by arpruss** [comment]
But one would need some way to specify the entity involved, right?

**Comment by Dodilei** [comment]
It works like:
/execute [entity] [relative coords] [command]

In the entity field you use @p, @a, @e (in 1.8) to specify, the nearest player, a random player or all entities. So the entity is already specified in the command.

**Comment by Dodilei** [comment]
Other thing that would work is adding the possibility of DataTags in commands like setblock, this way you could set a command block with a in-game command and a redstone block near it so it would execute the command, and then right after just clear the twk blocks, it would require just two blocks of space.

**Comment by arpruss** [comment]
You might be able to use spawnEntity() to generate a command block TileEntity. I haven't tried that. You sound like you know more about Minecraft than I do. 

I wonder if we couldn't just allow for arbitrary slash commands.

**Comment by Dodilei** [comment]
I will try.
Haha, I used to play a lot woth commands in Mc
And you certainly know more about programming than I do :p

**Comment by Dodilei** [comment]
I think there's no "TileEntity" in the entity.py file of mcpi, BUT MinecartCommandBlocks exists, I think I can make it work.

**Comment by Dodilei** [comment]
Looking at the Minecraft class methods I realized the commands GetBlockWithNBT and SetBlockWithNBT exist.
They work exactly the way I want.

Thank you very much :)
