### ISSUE TITLE
Implement entity.getName to find entity name?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arpruss/raspberryjammod#40]
The RaspberryJuice plugin support the entity.getName(entity-d) call to return the name of players or other entities.  It is useful in a multiplayer setup.  Would you be willing to add this command to RaspberryJam mod?

**Comment by arpruss** [comment]
If you use my version of mcpi/minecraft.pi, entity.getName() should work fine. Behind the scenes it works differently, though: it uses entity.getNameAndUUID().

**Comment by arpruss** [comment]
Fixed.

**Comment by petterreinholdtsen** [comment]
Aha.  Thank you very much.  I do not use any library, I talk directly, so it did not help to have a remapped library call in your library. :)  Will adjust my code to use your method if the other fail.
