### ISSUE TITLE
How to compile the proyect in 1.12.2 

### ISSUE THREAD

**Issue by oigreslol** [arpruss/raspberryjammod#46]
How can i build with 1.12.2 when i use gradlew build in the main directory of the proyect that I downloaded but it compile a version for 1.8 or 1.9.
i change the version in buildgradle.properti to 1.12 and it have problems to compile in the gradlew build like import net.minecraft.util.BlockPos;import net.minecraft.util.IChatComponent;import net.minecraft.network.play.server.S43PacketCamera;

**Comment by arpruss** [comment]
You should run build.sh instead of editing anything and it will build all the versions. But there is a pending pull request to fix some things in the build process.

**Comment by oigreslol** [comment]
thank you, but I'm a very very noob person, and I did sh fast.sh on cygwin(windows) and it doesn't generate the file 1.12.2 plsss can you be more specific?, plsss
 :(

**Comment by arpruss** [comment]
There may be something wrong with the build system.

**Comment by oigreslol** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\sergio\Desktop\ModMinecraft\raspberryjammod-master\112\build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project '112'.
> You must specify the full forge version, including MC version in your build.gradle. Example: 1.12.2-14.23.5.2811

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.733 secs
cp: no se puede efectuar `stat' sobre 'build/libs/RaspberryJamMod.jar': No such file or directory
mkdir: no se puede crear el directorio «C:\\Users\\sergio\\AppData\\Roaming/.minecraft/mods»: File exists
mkdir: no se puede crear el directorio «C:\\Users\\sergio\\AppData\\Roaming/.minecraft/mods/1.12»: File exists
mkdir: no se puede crear el directorio «C:\\Users\\sergio\\AppData\\Roaming/.minecraft/mods/1.12.1»: File exists
mkdir: no se puede crear el directorio «C:\\Users\\sergio\\AppData\\Roaming/.minecraft/mods/1.12.2»: File exists
cp: no se puede efectuar `stat' sobre 'build/libs/RaspberryJamMod.jar': No such file or directory
cp: no se puede efectuar `stat' sobre 'build/libs/RaspberryJamMod.jar': No such file or directory
cp: no se puede efectuar `stat' sobre 'build/libs/RaspberryJamMod.jar': No such file or directory


**this is my error log**  I don't know what it is happening and is the last version

**Comment by oigreslol** [comment]
Solved It:

**step1**:You need to update your Java to 8 and jdk to the last version and change your JAVA_HOME and PATH, you can find into internet how to change the path of java version, you need to verificated that the version of java is update, so you enter to a console and put javac -version and if it is yours version that you download (the latest version of java jdk), you are able to continue to the next step.
**step2**:after that you need to chage the fast.sh into the 112 folder, in the **sh gradlew --offline build** change to **sh gradlew build** after that change into the build.gradle the version, the version need to stay in :
**minecraft {**
   ** version = "1.10.2-12.18.2.2147"
    **runDir = "run"
**}**
it version works to compile a version for 1.12.2 1.11.1 and the others 
it sh programm put the files into the %appdata%.minecraft/mods and /1.12.2/ folder, it doesn't import if after finish the sh fast.sh said that is impossible to create the directory.
:) if someone is using this incredible mod a big hug

**Comment by oigreslol** [comment]
Solved It:

**step1**:You need to update your Java to 8 and jdk to the last version and change your JAVA_HOME and PATH, you can find into internet how to change the path of java version, you need to verificated that the version of java is update, so you enter to a console and put javac -version and if it is yours version that you download (the latest version of java jdk), you are able to continue to the next step.
**step2**:after that you need to chage the fast.sh into the 112 folder, in the **sh gradlew --offline build** change to **sh gradlew build** after that change into the build.gradle the version, the version need to stay in :
**minecraft {**
   ** version = "1.10.2-12.18.2.2147"
    **runDir = "run"
**}**
it version works to compile a version for 1.12.2 1.11.1 and the others 
it sh programm put the files into the %appdata%.minecraft/mods and /1.12.2/ folder, it doesn't import if after finish the sh fast.sh said that is impossible to create the directory.
:) if someone is using this incredible mod a big hug

**Comment by Marcinosoft** [comment]
Specyfying version "1.10.2-12.18.2.2147" for 111 and 112 works, but keep in mind that plugins for 1.11 and 1.12 will be in fact based on game version 1.10. Just look into target jar files - classes are the same. Difference is only within mcmod.info - mcversion. If you really want to compile 1.11 mod and 1.12 mod based on MC 1.11 and MC 1.12 sources, then you have to specify correct version within 111\build.gradle and 112\build.gradle files. Moreover for 1.12 you have to change dependecy from net.minecraftforge.gradle:ForgeGradle:2.2-SNAPSHOT to net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT as long 2.2 does not support MC higher then 1.11.  Alle the things I included within my last pull request: https://github.com/arpruss/raspberryjammod/pull/42. I also implemented few fancy methods to be able to list entities near player and remove them by type or specified id. This way you can for instance make creeper dissappear when distance between player and creeper is for example less than 10 blocks, or even for example replace creepers with cows when creeeper distance is less than for example 10 blocks. I needed those functionalities for my little Python students, who were able to spawn entities, but sadly wasn't able to remove them from Python. This also allowed me for example to implement multiplayer game where players goal is to remove as many creepers as they can without touch them, just by running near random generated creepers on closed arena. Player who eliminate more creepers - wins. Ability to list entities near player also makes possible to answer a question: is any cow or horse near player, and where it is ? I think this pull request gives another funny functionalities to this amazing mod. Until it will be merged you can get merged version from this fork: https://github.com/Marcinosoft/raspberryjammod
