### ISSUE TITLE
Use this mod on servers that aren't your own

### ISSUE THREAD

**Issue by smokeytube** [arpruss/raspberryjammod#54]
There's an anarchy server that allows modifications like this on the server I play on and I want to make a chatbot that interacts with different players. The program works fine on singleplayer worlds but when I try to activate it on that anarchy server it just says "Unknown command" when I try to run the script. I understand that the server has to have the raspberryjammod to run but I was wondering if there is any way I can use this mod client side.

**Comment by arpruss** [comment]
Go to the mod settings: there is a read-only option where any changes the mod makes are local-only.

**Comment by smokeytube** [comment]
Thank you so much, it worked.
