### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by kgsensei** [arpruss/raspberryjammod#55]
Is there a way to access item data inside a players inventory? For example: {Items:[dirt:64]}. I'm not trying to see other players inventories just my own. If not is there a way I could code it in?

**Comment by kgsensei** [comment]
No longer relevant.

**Comment by smokeytube** [comment]
Did you figure this out? Id like to know how you did it.

**Comment by kgsensei** [comment]
No unfortunately I never found a way to do that.

**Comment by Juloup78** [comment]
I think think you could use pyautogui to open the inventory and check for image that correspond to items

**Comment by smokeytube** [comment]
that would be quite a crappy way of doing it, it's slow and if you are using texture packs then it's useless.
