### ISSUE TITLE
Cannot run program "python".

### ISSUE THREAD

**Issue by jeQuentY** [arpruss/raspberryjammod#60]
I'm running the 1.12.2 version of the mod on Ubuntu 20.04 and I get this error all the time.

![image](https://user-images.githubusercontent.com/83346646/137945970-dd2a31d2-5f13-4ea7-a1fc-397bacb7820a.png)

I'm guessing it's because python isn't installed "to path". I've got everything working on my windows machine.

**Comment by arpruss** [comment]
Do you have python installed? What happens when you run python from the commandline?

**Comment by jeQuentY** [comment]
Yeah, python3.8.10 is installed. I also rebooted the system in case that had something to do with it but it won't work.

**Comment by arpruss** [comment]
Does running "python" from the commandline work, or do you need to type "python3"?

**Comment by jeQuentY** [comment]
I need to write python3

**Comment by arpruss** [comment]
You can go to the options for RaspberryJamMod and change it to python3 there. Or you can add a soft-link from python3 to python.

**Comment by jeQuentY** [comment]
Thanks a lot for your help, after a bit of trial and error i managed to get everything working. I'm really new to ubuntu and i have to learn a lot :) . Have a good one <3
